### ISSUE TITLE
hubzilla-website.zip leads to broken images

### ISSUE THREAD

**Issue by encyclomundi** [anaqreon/hubzilla-website#15]
I deleted previous webpage
I imported hubzilla-website.zip
Site loads, but images are broken.
e9bb111

**Comment by HappyPony** [comment]
Have you "images are broken" yet? May be are images-links not broken, but https://hubzilla.de , where are images hosted was offline?

**Comment by anaqreon** [comment]
Sorry for the tumult lately. I'm trying to simplify things with the goal of simpler translations, which catalyzed all this change. Along the way I'm discovering new issues including the one I mention here:

https://grid.reticu.li/display/dbd972f36638aa1dbb6c0b898fcfda7273d40078c0bca43ac337fe89d73867b7@grid.reticu.li
